version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install -g gulp
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - gulp build
  post_build:
    commands:
      - echo Build completed on `date`
