version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install -g gulp
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - gulp build
      - echo Building the Docker image...
      - docker build -t stibi/aws-pipeline-nodejs-hello-world:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image
      - docker push stibi/aws-pipeline-nodejs-hello-world:latest
artifacts:
  files:
    - dist/*
